# Generated by Django 5.0.1 on 2024-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=100)),
                ('cityName', models.CharField(max_length=30)),
                ('countryName', models.CharField(max_length=30)),
                ('msgContent', models.CharField(max_length=250)),
                ('msgDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
