# Generated by Django 5.0.1 on 2024-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobileNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msgDate',
            field=models.DateField(),
        ),
    ]
